defaults:
  - task_config_base
  - measurements:
    - distance_to_goal
    - distance_to_goal_reward
    - success
    - did_multi_agents_collide
    - num_steps
    - top_down_map
    - spl
    - psc
    - human_collision
  - _self_

type: MultiAgentPointNavTask-v0
end_on_success: True
reward_measure: "distance_to_goal_reward"
success_measure: "spl"
goal_sensor_uuid: pointgoal_with_gps_compass
measurements:
  success:
    success_distance: 0.4
