# @package _global_

defaults:
  - falcon_hm3d_real_world
  - _self_

habitat_baselines:
  rl:
    auxiliary_losses:
      people_counting:
        max_human_num: 6
        loss_scale: 0.1
      guess_human_position:
        max_human_num: 6
        position_dim: 2
        loss_scale: 0.1
      future_trajectory_prediction:
        max_human_num: 6
        future_step: 4
        loss_scale: 0.1
